### ISSUE TITLE
Using tags instead of statsd metrics?

### ISSUE THREAD

**Issue by jacobbednarz** [ylansegal/nunes-datadog#1]
Have you explored using the [datadog tagging](http://docs.datadoghq.com/guides/dogstatsd/#tags) approach instead of just using the statsd style metric that nunes spits out?

I'm interested to see this because I'd like to be able to filter on the various dynamic pieces of data instead of just doing a graph per incoming metric.

**Comment by ylansegal** [comment]
I haven't, but I think that would be much better and easier to create graphs in Datadog.

I may have some time later in the week to look into it, or would also welcome a PR.

**Comment by ylansegal** [comment]
@jacobbednarz I took a look at it, but it's more difficult than I thought. 

Byy the time Nunes propert send the metrics to the adapter, it already incorporates the information that we want to be in tags (e.g. controller, action). 

For example, in https://github.com/jnunemaker/nunes/blob/master/lib/nunes/subscribers/action_controller.rb#L40

Instead of:

``` ruby
timing "action_controller.controller.#{controller}.#{action}.runtime.total", runtime
```

we would want something like:

``` ruby
tags = ["controller:#{controller}", "action:#{action}"]
timing "action_controller.runtime.total", runtime, tags: tags
```

That would mean forking Nunes and making a version that is specialized to Datadog.

**Comment by ylansegal** [comment]
A quick search for a project already doing a Datadog-specific integration, I found:

https://github.com/metova/datadoge

**Comment by jacobbednarz** [comment]
I also looked into this and I couldn't work out how to nicely work it into the existing nunes setup. I think this will need to be a custom thing so I'll probably just fork it and go from there.

I have seen https://github.com/metova/datadoge before however it doesn't cover most of the things I am looking to instrument so I'll probably just pass on that one.

Thanks anyway!

**Comment by jacobbednarz** [comment]
fwiw, i've completed this over at https://github.com/jacobbednarz/nunes (specifically https://github.com/jacobbednarz/nunes/commit/f9dc38a7baea9415558d5a6db535b40a6e908010) if you are interested.

**Comment by ylansegal** [comment]
@jacobbednarz Thanks for taking the time to update: The changes look simple 👍

**Comment by jacobbednarz** [comment]
Wasn't too bad. I did update the default adapter though instead of relying on your adapter (just because it was forked already).
